# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dc6409787b9428ab37108daccee0adb878744b0abf16261aea22eb6356c05b503bab19fa4f7baa5a4203e1aa3758f26a7cac4eeffdf19d38b7f6a8223ed74707
  consumer_key: <%=  ENV["CONSUMER_KEY"] %>
  consumer_secret: <%=  ENV["CONSUMER_SECRET"] %>
  access_token: <%=  ENV["ACCESS_TOKEN"] %>
  access_token_secret: <%=  ENV["ACCESS_TOKEN_SECRET"] %>
  codea_tag_api_token: <%=  ENV["CODEA_TAG_API_TOKEN"] %>
  
test:
  secret_key_base: 37af2b5db5a1615507f54bbe8dacb62c34ff4669cdde00166ae965e5ec2e2e850fecded43a79a06594a02cd659dbd50a19be197f35605a38d8b124ca4a024df4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
